# Generated by Django 4.1.1 on 2022-09-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Authors",
            new_name="Author",
        ),
    ]
