# Generated by Django 4.1.1 on 2022-09-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_rename_authors_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genrej",
            new_name="genre",
        ),
    ]
